version: "3.7"
services:
    cms:
        build:
            context: .
            dockerfile: Dockerfile
        image: ceiboo-harbour
        container_name: ceiboo-harbour-src-bin
        volumes:
            - ./src:/app/src
        command: ["./cms"]